baseurl = "https://ctop.sh"
languageCode = "en-us"
title = "ctop"
theme = "hugo-creative-theme"
googleAnalytics = "UA-93338213-1"

[params]

	name = "Bradley Cicenas"
	description = "Commandline monitoring for containers"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "ctop"

	# Hero section
	[params.hero]
		slogan     = ""
		subtitle   = "concise commandline monitoring for containers"
		buttonText = "get ctop"
